sudo: required

services:
  - docker

before_install:
  - docker pull pombase/canto-base:v7

branches:
  only:
    - master
    - metagenotype-dev

# this runs "make test" inside a Docker container using the
# pombase/canto-base:v7 image
script: ./etc/docker-run-tests.sh
