# configuration used to set up a populated database for testing
"Model::TrackModel":
  schema_class: 'PomCur::TrackDB'
  connect_info:
     - "dbi:SQLite:dbname=t/data/track_db_test_template.sqlite3"
