test_mode: 1
test_config:
  data_dir: "t/data"
  curation_spreadsheet: "t/data/community_curation_stats_small.txt"
  organism:
    genus: Schizosaccharomyces
    species: pombe
    taxonid: 4896
  test_genes_file: "t/data/pombe_genes.txt"
  test_go_obo_file: "t/data/go_small.obo"
  test_relationship_obo_file: "t/data/ro.obo"
  test_cases:
    empty_db:
    0_curs: []
    1_curs:
       - curs_key: aaaa0001
         first_contact_email: "nick.rhind@umassmed.edu"
         uniquename: 19664060
    3_curs:
       - curs_key: aaaa0002
         first_contact_email: "hoffmacs@bc.edu"
         uniquename: 19686603
       - curs_key: aaaa0003
         first_contact_email: "kevin.hardwick@ed.ac.uk"
         uniquename: 19436749
         submitter_email: "kevin.hardwick@ed.ac.uk"
         submitter_name: "Kevin Hardwick"
       - curs_key: aaaa0004
         first_contact_email: "kevin.hardwick@ed.ac.uk"
         uniquename: 18426916
         submitter_email: "fred.smith@ed.ac.uk"
         submitter_name: "Fred Smith"
         current_gene: "SPCC1739.10"
         genes:
           - "cdc11"
           - "SPCC1739.10"
    curs_annotations_1:
       - curs_key: aaaa0005
         first_contact_email: "kevin.hardwick@ed.ac.uk"
         uniquename: 18426916
         submitter_email: "fred.smith@ed.ac.uk"
         submitter_name: "Fred Smith"
         current_gene: "SPCC1739.10"
         genes:
           - "cdc11"
           - "SPCC1739.10"
           - "SPAC3A11.14c"
         annotations:
           - type: cellular_component
             status: new
             genes(Gene:primary_identifier):
               - SPCC1739.10
             pub(Pub:uniquename): 18426916
             data:
               evidence_code: IMP
               term_ontid: GO:0055085
           - type: cellular_component
             status: new
             genes(Gene:primary_identifier):
               - SPAC3A11.14c
             pub(Pub:uniquename): 18426916
             data:
               evidence_code: IPI
               term_ontid: GO:0030133
               with_gene: SPCC1739.11c
