test_mode: 1
test_config:
  data_dir: "t/data"
  curation_spreadsheet: "t/data/community_curation_stats_small.txt"
  test_genes_file: "t/data/pombe_genes.txt"
  test_go_obo_file: "t/data/go_small.obo"
  test_cases:
    empty_db:
    '0_curs': []
    '1_curs':
       - curs_key: aaaa0001
         first_contact_email: "nick.rhind@umassmed.edu"
         pubmedid: 19664060
    '3_curs':
       - curs_key: aaaa0002
         first_contact_email: "hoffmacs@bc.edu"
         pubmedid: 19686603
       - curs_key: aaaa0003
         first_contact_email: "kevin.hardwick@ed.ac.uk"
         pubmedid: 19436749
         submitter_email: "kevin.hardwick@ed.ac.uk"
         submitter_name: "Kevin Hardwick"
       - curs_key: aaaa0004
         first_contact_email: "kevin.hardwick@ed.ac.uk"
         pubmedid: 18426916
         submitter_email: "fred.smith@ed.ac.uk"
         submitter_name: "Fred Smith"
         current_gene: "SPCC1739.10"
         genes:
           - "cdc11"
           - "SPCC1739.10"
    'curs_annotations_1':
       - curs_key: aaaa0005
         first_contact_email: "kevin.hardwick@ed.ac.uk"
         pubmedid: 18426916
         submitter_email: "fred.smith@ed.ac.uk"
         submitter_name: "Fred Smith"
         current_gene: "SPCC1739.10"
         genes:
           - "cdc11"
           - "SPCC1739.10"
         annotations:
           - type: go_component
             status: new
             'genes(Gene:primary_identifier)':
               - 'SPCC1739.10'
             'pub(Pub:pubmedid)': 18426916
             data:
               some_key: 'some_value'
