test_mode: 1
test_config:
  data_dir: "t/data"
  track_test_0_curs_db: "t/data/track_db_0_curs_test_template.sqlite3"
  track_test_1_curs_db: "t/data/track_db_1_curs_test_template.sqlite3"
  track_test_3_curs_db: "t/data/track_db_3_curs_test_template.sqlite3"
  curation_spreadsheet: "t/data/community_curation_stats_small.txt"
  test_genes_file: "t/data/pombe_genes.txt"
  test_cases:
    empty_db:
    '0_curs': []
    '1_curs':
       - curs_key: aaaa0001
         first_contact_email: "nick.rhind@umassmed.edu"
         pubmedid: 19664060
    '3_curs':
       - curs_key: aaaa0002
         first_contact_email: "hoffmacs@bc.edu"
         pubmedid: 19686603
       - curs_key: aaaa0003
         first_contact_email: "kevin.hardwick@ed.ac.uk"
         pubmedid: 19436749
         submitter_email: "kevin.hardwick@ed.ac.uk"
         submitter_name: "Kevin Hardwick"
       - curs_key: aaaa0004
         first_contact_email: "kevin.hardwick@ed.ac.uk"
         pubmedid: 18426916
         submitter_email: "fred.smith@ed.ac.uk"
         submitter_name: "Fred Smith"
         current_gene: "SPCC1739.10"
         genes:
           - "cdc11"
           - "SPCC1739.10"
    'curs_annotations_1':
       - curs_key: aaaa0005
         first_contact_email: "kevin.hardwick@ed.ac.uk"
         pubmedid: 18426916
         submitter_email: "fred.smith@ed.ac.uk"
         submitter_name: "Fred Smith"
         current_gene: "SPCC1739.10"
         genes:
           - "cdc11"
           - "SPCC1739.10"
         annotations:
           - type: go_component
             status: new
             'Pub:pubmedid': 18426916
             data:
               'Gene:primary_identifier': "SPCC1739.10"
