test_mode: 1
test_config:
  data_dir: "t/data"
  curation_spreadsheet: "t/data/community_curation_stats_small.txt"
  organisms:
    - genus: Schizosaccharomyces
      species: pombe
      taxonid: 4896
    - genus: Saccharomyces
      species: cerevisiae
      taxonid: 4932
  test_chado_db: "chado_test_db.sqlite3"
  test_genes_file: "t/data/pombe_genes.txt"
  test_genes_file_organism_2: "t/data/cerevisiae_genes.txt"
  test_go_obo_file: "t/data/go_small.obo"
  test_phenotype_obo_file: "t/data/phenotype_small.obo"
  test_psi_mod_obo_file: "t/data/psi_mod_small.obo"
  test_pco_obo_file: "t/data/pco_small.obo"
  test_relationship_obo_file: "etc/ro.obo"
  test_pubmed_xml: 'entrez_pubmed.xml'
  test_extra_publication: 'pubmed_18910671.xml'
  test_uniprot_entries: 'uniprot_lookup.xml'
  test_quickgo_gaf: 'pubmed_11676915_annotation.gaf'
  test_cases:
    empty_db:
    0_curs: []
    1_curs:
       - curs_key: aaaa0001
         first_contact_email: "nick.rhind@umassmed.edu"
         uniquename: PMID:19664060
    3_curs:
       - curs_key: aaaa0002
         first_contact_email: "hoffmacs@bc.edu"
         uniquename: PMID:19686603
       - curs_key: aaaa0003
         first_contact_email: "kevin.hardwick@ed.ac.uk"
         uniquename: PMID:19436749
         submitter_email: "kevin.hardwick@ed.ac.uk"
         submitter_name: "Kevin Hardwick"
       - curs_key: aaaa0004
         first_contact_email: "kevin.hardwick@ed.ac.uk"
         uniquename: PMID:18426916
         submitter_email: "fred.smith@ed.ac.uk"
         submitter_name: "Fred Smith"
         current_gene: "SPCC1739.10"
         genes:
           - "cdc11"
           - "SPCC1739.10"
    curs_annotations_1:
       - curs_key: aaaa0005
         first_contact_email: "kevin.hardwick@ed.ac.uk"
         uniquename: PMID:18426916
         submitter_email: "fred.smith@ed.ac.uk"
         submitter_name: "Fred Smith"
         current_gene: "SPCC1739.10"
         genes:
           - "cdc11"
           - "SPCC1739.10"
           - "SPAC3A11.14c"
         annotations:
           - type: biological_process
             status: new
             genes(Gene:primary_identifier):
               - SPCC1739.10
             pub(Pub:uniquename): PMID:18426916
             data:
               evidence_code: IMP
               term_ontid: GO:0055085
           - type: cellular_component
             status: new
             genes(Gene:primary_identifier):
               - SPAC3A11.14c
             pub(Pub:uniquename): PMID:18426916
             data:
               evidence_code: IPI
               term_ontid: GO:0030133
               with_gene: SPCC1739.10
    curs_annotations_2:
       - curs_key: aaaa0006
         first_contact_email: "henar@usal.es"
         uniquename: PMID:18426916
         submitter_email: "henar@usal.es"
         submitter_name: "Henar Valdivieso"
         current_gene: "SPCC576.16c"
         genes:
           - "SPCC576.16c"
         annotations:
           - type: biological_process
             status: new
             genes(Gene:primary_identifier):
               - SPCC576.16c
             pub(Pub:uniquename): PMID:18426916
             data:
               evidence_code: IMP
               term_ontid: GO:0055085
       - curs_key: aaaa0007
         first_contact_email: "Ken.Sawin@ed.ac.uk"
         uniquename: PMID:19756689
         submitter_email: "Ken.Sawin@ed.ac.uk"
         submitter_name: "Ken Sawin"
         current_gene: "SPCC576.16c"
         genes:
           - "SPCC576.16c"
           - primary_identifier: "SPAC27D7.13c"
             alleles:
               - primary_identifier: 'SPAC27D7.13c:allele-1'
                 name: ssm4delta
                 description: deletion
                 type: existing
               - primary_identifier: 'SPAC27D7.13c:allele-2'
                 name: R344A
                 description: R344A
                 type: existing
               - name: ssm4-D4
                 description: 'del_100-200'
                 type: new
               - description: 'del_200-300'
                 type: new
           - "SPBC14F5.07"
           - primary_identifier: "SPCC63.05"
             alleles:
               - name: SPCC63.05-unk
                 description: unknown
                 type: new
         annotations:
           - type: biological_process
             status: new
             genes(Gene:primary_identifier):
               - SPAC27D7.13c
             pub(Pub:uniquename): PMID:19756689
             data:
               evidence_code: IMP
               term_ontid: GO:0055085
               term_suggestion:
                 name: miscellaneous transmembrane transport
                 definition: The process in which miscellaneous stuff is transported from one side of a membrane to the other.
           - type: biological_process
             status: new
             genes(Gene:primary_identifier):
               - SPBC14F5.07
             pub(Pub:uniquename): PMID:19756689
             data:
               evidence_code: IPI
               term_ontid: GO:0034763
               with_gene: SPCC576.16c
               annotation_extension: "annotation_extension=exists_during(GO:0051329),annotation_extension=has_substrate(GeneDB_Spombe:SPBC1105.11c),annotation_extension=requires_feature(Pfam:PF00564),residue=T31,residue=T586(T586,X123),qualifier=NOT,condition=PCO:0000012,allele=SPAC9.02cdelta(deletion)"
           - type: molecular_function
             status: new
             genes(Gene:primary_identifier):
               - SPBC14F5.07
             pub(Pub:uniquename): PMID:19756689
             data:
               evidence_code: IDA
               term_ontid: GO:0022857
           - type: genetic_interaction
             status: new
             genes(Gene:primary_identifier):
               - SPCC63.05
             pub(Pub:uniquename): PMID:19756689
             data:
               evidence_code: Synthetic Haploinsufficiency
               interacting_genes:
                 - primary_identifier: SPBC14F5.07
                 - primary_identifier: SPAC27D7.13c
           - type: phenotype
             status: new
             alleles(Allele:description):
               - deletion
             pub(Pub:uniquename): PMID:19756689
             data:
               evidence_code: Epitope-tagged protein immunolocalization experiment data
               term_ontid: FYPO:0000013
               expression: Overexpression
               conditions:
                 - 'PCO:0000004'
           - type: phenotype
             status: new
             alleles(Allele:description):
               - del_100-200
             pub(Pub:uniquename): PMID:19756689
             data:
               evidence_code: Co-immunoprecipitation experiment
               term_ontid: FYPO:0000017
           - type: post_translational_modification
             status: new
             genes(Gene:primary_identifier):
               - SPCC63.05
             pub(Pub:uniquename): PMID:19756689
             data:
               evidence_code: ISS
               term_ontid: MOD:01157
  
