name: Canto tests

on: [ push, pull_request ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: pull base image
      run: docker pull pombase/canto-base:v12
    - name: run make test inside a Docker container
      run: ./etc/docker-run-tests.sh
